---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  project: default
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: "*"
    helm:
      values: |
        controller:
          service:
            type: LoadBalancer
            externalTrafficPolicy: Local
          ingressClassResource:
            default: true
  destination:
    server: https://kubernetes.default.svc
    namespace: network
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true