apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adguard
  namespace: argocd
  labels:
    app.kubernetes.io/name: adguard
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/component: network
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/meta-boy/homelab.git
    targetRevision: HEAD
    path: charts/adguard
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: service.type
          value: LoadBalancer
        - name: persistence.work.storageClass
          value: longhorn
        - name: persistence.conf.storageClass
          value: longhorn
        - name: service.dnsLoadBalancerIP
          value: "192.168.1.242"
        - name: service.webLoadBalancerIP
          value: "192.168.1.242"
  destination:
    server: https://kubernetes.default.svc
    namespace: network
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s