apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - sealed-secret.yaml
  - temporal-statefulset.yaml
  - temporal-service.yaml
  - temporal-ui-deployment.yaml
  - temporal-ui-service.yaml
