apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: temporal-secret
  namespace: temporal
spec:
  encryptedData:
    # TODO: Seal these values using kubeseal
    # Values to encrypt:
    # DB: postgres12
    # DB_PORT: "5432"
    # POSTGRES_USER: <postgres-username>
    # POSTGRES_PWD: <postgres-password>
    # POSTGRES_SEEDS: postgres.postgres.svc.cluster.local
    # DBNAME: temporal
    DB: PLACEHOLDER_TO_BE_SEALED
    DB_PORT: PLACEHOLDER_TO_BE_SEALED
    POSTGRES_USER: PLACEHOLDER_TO_BE_SEALED
    POSTGRES_PWD: PLACEHOLDER_TO_BE_SEALED
    POSTGRES_SEEDS: PLACEHOLDER_TO_BE_SEALED
    DBNAME: PLACEHOLDER_TO_BE_SEALED
  template:
    metadata:
      name: temporal-secret
      namespace: temporal
    type: Opaque
