apiVersion: v1
kind: Service
metadata:
  name: temporal
  namespace: temporal
spec:
  type: NodePort
  selector:
    app: temporal
  ports:
  - name: frontend
    port: 7233
    targetPort: 7233
    nodePort: 30233
    protocol: TCP
