apiVersion: v1
kind: Secret
metadata:
  name: postgres
  labels:
    app: {{ include "postgres.name" . }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ required "Environment variable POSTGRES_PASSWORD is required" (env "POSTGRES_PASSWORD" | b64enc) }}
