apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus.fullname" . }}-config
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.config.global.scrape_interval }}
      evaluation_interval: {{ .Values.config.global.evaluation_interval }}
    
    scrape_configs:
    {{- range .Values.config.scrape_configs }}
      - job_name: {{ .job_name | quote }}
        {{- if .static_configs }}
        static_configs:
        {{- range .static_configs }}
          - targets:
            {{- range .targets }}
              - {{ . | quote }}
            {{- end }}
        {{- end }}
        {{- end }}
        {{- if .kubernetes_sd_configs }}
        kubernetes_sd_configs:
        {{- toYaml .kubernetes_sd_configs | nindent 10 }}
        {{- end }}
        {{- if .scheme }}
        scheme: {{ .scheme }}
        {{- end }}
        {{- if .tls_config }}
        tls_config:
        {{- toYaml .tls_config | nindent 10 }}
        {{- end }}
        {{- if .bearer_token_file }}
        bearer_token_file: {{ .bearer_token_file }}
        {{- end }}
        {{- if .relabel_configs }}
        relabel_configs:
        {{- toYaml .relabel_configs | nindent 10 }}
        {{- end }}
    {{- end }}