apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-arc-token
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical-secret-store
    kind: ClusterSecretStore
  target:
    name: github-arc-token
    creationPolicy: Owner
  data:
    - secretKey: github_token
      remoteRef:
        key: GITHUB_ARC_PAT
