apiVersion: v1
kind: Service
metadata:
  name: registry-server
  namespace: docker-registry
  labels:
    app: registry-server
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30500
      protocol: TCP
      name: http
  selector:
    app: registry-server
