{{- if .Values.persistence.work.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "adguard.fullname" . }}-work-pvc
  labels:
    {{- include "adguard.labels" . | nindent 4 }}
  {{- with .Values.persistence.work.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.work.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.work.size }}
  {{- if .Values.persistence.work.storageClass }}
  storageClassName: {{ .Values.persistence.work.storageClass }}
  {{- end }}
{{- end }}
---
{{- if .Values.persistence.conf.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "adguard.fullname" . }}-conf-pvc
  labels:
    {{- include "adguard.labels" . | nindent 4 }}
  {{- with .Values.persistence.conf.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.conf.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.conf.size }}
  {{- if .Values.persistence.conf.storageClass }}
  storageClassName: {{ .Values.persistence.conf.storageClass }}
  {{- end }}
{{- end }}