apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- prometheus-rbac.yaml
- prometheus-config.yaml
- prometheus-pvc.yaml
- prometheus-statefulset.yaml
- prometheus-service.yaml
- pushgateway-deployment.yaml
- pushgateway-service.yaml
- grafana-config.yaml
- grafana-pvc.yaml
- grafana-deployment.yaml
- grafana-service.yaml
- grafana-ingress.yaml
