apiVersion: v2
name: nginx-ingress
description: Nginx Ingress Controller for homelab
type: application
version: 1.0.0
appVersion: "1.12.0"

dependencies:
  - name: ingress-nginx
    version: 4.12.0
    repository: https://kubernetes.github.io/ingress-nginx
