apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docker-registry-ui
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/meta-boy/homelab.git
    targetRevision: main
    path: apps/docker-registry-ui/base
  destination:
    server: https://kubernetes.default.svc
    namespace: docker-registry
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
