apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dam-scripts-logs
  namespace: dam-scripts
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dam-scripts-ocr-images
  namespace: dam-scripts
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
